import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/context/auth-context";
import { AuthModalProvider } from "@/context/auth-modal-context";
import AuthModal from "@/components/auth/auth-modal";

import { LocaleProvider } from "@/context/locale-context";
import { notFound } from 'next/navigation';

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  // Ensure that the incoming `locale` is valid
  if (!['en', 'th'].includes(locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`${inter.variable} font-sans antialiased`}
      >
        <LocaleProvider initialLocale={locale as 'en' | 'th'}>
          <AuthProvider>
            <AuthModalProvider>
              {children}
              <AuthModal />
            </AuthModalProvider>
          </AuthProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}
